#!/usr/bin/env bash

# https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.4.0-amd64-netinst.iso

VERSION=${VERSION=13.4.0}
ARCH='amd64'
FLAVOR='standard'

declare -A ISO=(
  ['alpine']="https://dl-cdn.alpinelinux.org/alpine/v${VERSION}/releases/${ARCH}/alpine-${FLAVOR}-${VERSION}-${ARCH}.iso"
  ['debian']="https://cdimage.debian.org/debian-cd/current/${ARCH}/iso-cd/debian-${VERSION}-${ARCH}-netinst.iso"
)
# https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/x86/alpine-standard-3.23.3-x86.iso

echo ${ISO[debian]}
# wget ${ISO[debian]}

# https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/debian-13.4.0-arm64-netinst.iso

# https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.4.0-amd64-netinst.iso
#
