#!/bin/bash
cd $HOME/COMMON_CORE/minirt/

tmux new-session  -s mysession -n 'mandatory/parsing'\; \
    send 'cd mandatory/parsing; nvim .' ENTER \; \
    new-window -n "mandatory/rendering" \;\
    send 'cd mandatory/rendering; nvim .' ENTER \;\
  new-window -n "include" \; \
    send 'cd include; nvim .' ENTER \; \
  new-window -n "Makefile" \; \
    send 'nvim Makefile'  ENTER\; \
  new-window -n "tests" \;\
    send 'nvim rt/'\;
